version: '3.7'
services:
  app:
    build: .
    command: python main.py
    volumes:
      - .:/code
    env_file:
      - .env
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
volumes:
  postgres_data:
