"""initial migration

Revision ID: 267b688bb1fd
Revises: 
Create Date: 2022-11-16 20:14:41.431305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267b688bb1fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairs',
    sa.Column('giver_id', sa.Integer(), nullable=False),
    sa.Column('taker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['giver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['taker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('giver_id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wish_string', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishes')
    op.drop_table('rooms')
    op.drop_table('pairs')
    op.drop_table('users')
    # ### end Alembic commands ###
