"""addes pk to pairs

Revision ID: 378aa2ccd97e
Revises: e90d7529ef69
Create Date: 2022-11-18 20:02:50.710680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378aa2ccd97e'
down_revision = 'e90d7529ef69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pairs', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('pairs_pkey', 'pairs')
    op.create_primary_key("pairs_pkey", "pairs", ["giver_id", "room_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pairs', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
