"""addes room_id to users

Revision ID: 4566c5415cfb
Revises: 267b688bb1fd
Create Date: 2022-11-16 20:15:03.105985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4566c5415cfb'
down_revision = '267b688bb1fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'room_id')
    # ### end Alembic commands ###
