"""deletes wishes table & addes some columns

Revision ID: bf5365aa5ba0
Revises: 4566c5415cfb
Create Date: 2022-11-17 18:48:14.166614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5365aa5ba0'
down_revision = '4566c5415cfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishes')
    op.add_column('users', sa.Column('wish_string', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wish_string')
    op.create_table('wishes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wish_string', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishes_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='wishes_pkey')
    )
    # ### end Alembic commands ###
