"""addes room_id to pairs table

Revision ID: e90d7529ef69
Revises: db72a41484cf
Create Date: 2022-11-18 19:17:46.102522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90d7529ef69'
down_revision = 'db72a41484cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairs', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key('pairs_room_fk', 'pairs', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pairs_room_fk', 'pairs', type_='foreignkey')
    op.drop_column('pairs', 'room_id')
    # ### end Alembic commands ###
